# Generated by Django 3.2.2 on 2021-05-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.ImageField(upload_to='static/home')),
                ('heroTitle', models.TextField(max_length=50)),
                ('heroText', models.TextField(max_length=500)),
            ],
        ),
    ]
