# Generated by Django 3.2.2 on 2021-05-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_imageUrl', models.ImageField(upload_to='static/home/testimonials')),
                ('testimonial_text', models.TextField(max_length=100)),
                ('testimonial_person_name', models.TextField(max_length=30)),
                ('testimonial_person_designation', models.TextField(max_length=30)),
            ],
        ),
    ]
