# Generated by Django 3.2.2 on 2021-05-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='imageUrl',
            field=models.ImageField(upload_to='static/home/hero'),
        ),
    ]
