# Generated by Django 3.2.2 on 2021-05-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_hero_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial_text',
            field=models.TextField(max_length=10000),
        ),
    ]
