# Generated by Django 3.2.2 on 2021-05-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutme_image', models.ImageField(upload_to='static/aboutme/intro')),
                ('aboutme_title', models.TextField(max_length=30)),
                ('aboutme_text', models.TextField(max_length=1000)),
            ],
        ),
    ]
