# Generated by Django 3.2.2 on 2021-05-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.ImageField(upload_to='')),
                ('pic2', models.ImageField(upload_to='')),
                ('pic3', models.ImageField(upload_to='')),
            ],
        ),
    ]
